version: '3'
services:
   server:
     build:
       context: /mnt/docker/docker-compo
     image: apache:1.0
     ports:
     - "80:80"
     volumes:
     - "/mnt/docker/docker-compo://var/www/html"

